### ISSUE TITLE
Server Exits Ungracefully during stale session

### ISSUE THREAD

**Issue by michael-bey** [cedowens/MacShellSwift#1]
Server: Ubuntu 18.04 LTS

Description: 
When a session is not able to be exited cleanly (eg, reboot / removal / blocking), the server cannot accept new valid sessions and crashes.

To reproduce, stage a valid session in a virtual machine. Interact with the session, such as by doing `shell whoami`. Pause the VM and try to type "exit" to end interacting with the session. This will crash the server and give the following stacktrace:

Error:

```
Traceback (most recent call last):
  File "swiftshell-server.py", line 741, in <module>
    (connection, (ip,port)) = ssock.accept()
  File "/usr/lib/python3.6/ssl.py", line 1125, in accept
    server_side=True)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__

```

**Comment by cedowens** [comment]
Thanks for reporting. I suspect this has to do with the fact that the C2 connection is a continuous socket connection (as opposed to http/https beaconing) and so once the VM is paused the socket is killed. I'll take a look into how to have the server gracefully recognize the socket disconnection and exit.
